version: "3"
services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        volumes:
            - ./influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=stream
            - INFLUXDB_USER=chuck
            - INFLUXDB_USER_PASSWORD=chuck
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=toor
volumes:
    influxdb_data: