version: "3"
services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        volumes:
            - ./influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=stream
            - INFLUXDB_USER=chuck
            - INFLUXDB_USER_PASSWORD=chuck
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=toor
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - '5672:5672'
            - '8081:15692'
            - '15672:15672'
        volumes:
            - ./rabbitmq_data:/var/lib/rabbitmq
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - ./grafana_data:/var/lib/grafana
        depends_on:
            - influxdb
volumes:
    influxdb_data:
    grafana_data:
    rabbitmq_data: